### ISSUE TITLE
Clean up styling of the Date/Time Popup from Settings

### ISSUE THREAD

**Issue by ryanjduffy** [enactjs/agate-apps#31]
Current - Titanium:
![image](https://user-images.githubusercontent.com/788456/45443951-fc4d7480-b67a-11e8-99e3-6f6aa3323421.png)

Current - Carbon:
![image](https://user-images.githubusercontent.com/788456/45443979-0e2f1780-b67b-11e8-8fce-e048da916a48.png)

**Comment by teckliew** [comment]
https://github.com/enactjs/agate/pull/57
