### ISSUE TITLE
Add basic scroll on focus support to the Phone contact scroller

### ISSUE THREAD

**Issue by ryanjduffy** [enactjs/agate-apps#33]
Current contact scroller on Phone screen is based on `ui/Scroller` and therefore does not scroll items into view on focus. As a result, navigating via 5-way within the scroller can cause focus to "disappear" when it lands on an out-of-view component.

**Comment by sugardave** [comment]
I wasn't paying attention so my my agate-apps :pr: actually fixes https://github.com/enactjs/agate/issues/33
