### ISSUE TITLE
Implement new launcher layout

### ISSUE THREAD

**Issue by webOS101** [enactjs/agate-apps#46]
The existing launcher feels dated and plain.  Experiment with some ideas for something more compelling.

**Comment by haileyR** [comment]
![image](https://user-images.githubusercontent.com/8715394/46178449-be03a800-c26b-11e8-9032-1fd962700b08.png)

**Comment by lishammel** [comment]
closing - merged with https://github.com/enactjs/agate-apps/pull/53
