### ISSUE TITLE
Build HVAC Screen

### ISSUE THREAD

**Issue by Djspaceg** [enactjs/agate-apps#6]
Construct the Air Conditioner view. This will require Button, Icon, Image, Slider, and Picker.

![hvac](https://user-images.githubusercontent.com/386529/44816989-d44d1400-ab98-11e8-913d-8c577783655d.png)

**Comment by ryanjduffy** [comment]
Fixed by #8 and 4b2dbb1ac042948c209f41519764abe198e70f14
